'use client';

import { FormEvent, useMemo, useState } from 'react';

type Listing = { id: number; type: string; category: string; title: string; description: string; city: string; price?: string; hours: number; accent: string; featured?: boolean };

const listings: Listing[] = [
  { id: 1, type: 'SERVIÇO', category: 'Serviços', title: 'Gestão de tráfego para negócios locais', description: 'Anúncios que geram conversas e novos clientes para o seu negócio.', city: 'Dourados, MS', price: 'A partir de R$ 900', hours: 18, accent: 'yellow', featured: true },
  { id: 2, type: 'PROCURA', category: 'Procuro', title: 'Procuro designer para meu projeto', description: 'Preciso de identidade visual e artes para redes sociais.', city: 'Campo Grande, MS', hours: 10, accent: 'blue' },
  { id: 3, type: 'PRODUTO', category: 'Produtos', title: 'Planner 2026 para empreendedoras', description: 'Planejamento leve para organizar metas, rotina e vendas.', city: 'Online', price: 'R$ 49', hours: 6, accent: 'pink' },
  { id: 4, type: 'SERVIÇO', category: 'Serviços', title: 'Canva Designer para sua marca', description: 'Artes criativas e materiais que deixam sua comunicação mais bonita.', city: 'Dourados, MS', hours: 3, accent: 'lilac' },
  { id: 5, type: 'EVENTO', category: 'Eventos', title: 'Encontro de negócios no sábado', description: 'Uma manhã para trocar ideias, contatos e oportunidades.', city: 'Dourados, MS', price: 'Gratuito', hours: 20, accent: 'blue' },
  { id: 6, type: 'CONEXÃO', category: 'Conexões', title: 'Alguém especial por aí?', description: 'Gosto de viagens, natureza e boas conversas. Vamos nos conhecer?', city: 'Curitiba, PR', hours: 12, accent: 'pink' },
];
const categories = ['Todos', 'Serviços', 'Produtos', 'Procuro', 'Promoções', 'Eventos', 'Conexões'];
const Icon = ({ children }: { children: string }) => <span aria-hidden="true" className="icon">{children}</span>;

function ListingCard({ listing, onOpen }: { listing: Listing; onOpen: (listing: Listing) => void }) {
  return <article className={`paper-card ${listing.accent} ${listing.featured ? 'featured' : ''}`}><div className="card-top"><span className="tag">{listing.type}</span><button aria-label={`Mais opções para ${listing.title}`} className="more">⋮</button></div><h3>{listing.title}</h3><p>{listing.description}</p><div className="card-meta"><span>⌖ {listing.city}</span><span>◷ {listing.hours}h</span></div>{listing.price && <strong className="price">{listing.price}</strong>}<button className="card-link" onClick={() => onOpen(listing)}>Ver aviso <span>→</span></button></article>;
}

export default function Home() {
  const [screen, setScreen] = useState<'home' | 'search' | 'post' | 'promos' | 'more'>('home');
  const [query, setQuery] = useState(''); const [activeCategory, setActiveCategory] = useState('Todos');
  const [selected, setSelected] = useState<Listing | null>(null); const [published, setPublished] = useState<Listing | null>(null);
  const results = useMemo(() => listings.filter((l) => `${l.title} ${l.description} ${l.category} ${l.city}`.toLocaleLowerCase().includes(query.toLocaleLowerCase()) && (activeCategory === 'Todos' || l.category === activeCategory)), [query, activeCategory]);
  function publish(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const d = new FormData(event.currentTarget); setPublished({ id: 99, type: String(d.get('type') || 'AVISO').toUpperCase(), category: String(d.get('category') || 'Outros'), title: String(d.get('title') || 'Novo aviso'), description: String(d.get('description') || ''), city: String(d.get('city') || 'Online'), price: String(d.get('price') || ''), hours: 24, accent: 'yellow' }); }
  const changeScreen = (value: typeof screen) => { setScreen(value); setSelected(null); window.scrollTo({ top: 0, behavior: 'smooth' }); };

  return <main>
    <header className="topbar"><button className="brand" onClick={() => changeScreen('home')}><span>🏠</span><b>Mural<br />dos Aliados</b></button><nav className="desktop-nav" aria-label="Navegação principal"><button onClick={() => changeScreen('home')}>Início</button><button onClick={() => changeScreen('search')}>Buscar</button><button className="nav-post" onClick={() => changeScreen('post')}>📌 Colar no mural</button><button onClick={() => changeScreen('promos')}>Promoções</button></nav><button className="menu" aria-label="Abrir menu" onClick={() => changeScreen('more')}>☰</button></header>
    {screen === 'home' && <><section className="hero"><div><p className="eyebrow">📌 UM MURAL FEITO PARA A COMUNIDADE</p><h1>O que você<br /><em>precisa hoje?</em></h1><p className="hero-copy">Encontre serviços, produtos, oportunidades e pessoas no mural.</p></div><div className="hero-note"><span className="tape"/><strong>Seu aviso fica<br />no mural por 24h</strong><small>Simples, rápido e sem perfil obrigatório.</small></div></section><section className="quick-search" aria-label="Busca rápida"><Icon>⌕</Icon><input value={query} onChange={(e) => setQuery(e.target.value)} onFocus={() => setScreen('search')} placeholder="O que você procura hoje?" /><button onClick={() => setScreen('search')}>Buscar</button></section><section className="categories"><p>Explore por categoria</p><div>{categories.slice(1).map((category, index) => <button key={category} onClick={() => { setActiveCategory(category); changeScreen('search'); }}><span className={`category-icon ci-${index}`}>{['♧', '▱', '⌕', '♨', '✦', '♡'][index]}</span>{category}</button>)}</div></section><section className="section-header"><div><p className="eyebrow">O QUE ESTÁ NO MURAL</p><h2>Avisos de hoje</h2></div><button onClick={() => changeScreen('search')}>Ver todos →</button></section><section className="listing-grid">{listings.slice(0, 4).map((l) => <ListingCard key={l.id} listing={l} onOpen={setSelected} />)}</section><section className="callout"><div><span>📌</span><h2>Tem algo para compartilhar?</h2><p>Publique seu aviso e deixe a comunidade encontrar você.</p></div><button onClick={() => changeScreen('post')}>Colar no mural <span>→</span></button></section></>}
    {screen === 'search' && <section className="page narrow"><button className="back" onClick={() => changeScreen('home')}>← Voltar</button><p className="eyebrow">⌕ BUSCA NO MURAL</p><h1>Encontre o que<br /><em>você precisa.</em></h1><div className="search-large"><Icon>⌕</Icon><input autoFocus value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Busque por serviço, produto ou cidade" /></div><div className="filters">{categories.map((c) => <button className={activeCategory === c ? 'active' : ''} key={c} onClick={() => setActiveCategory(c)}>{c}</button>)}</div><div className="result-title"><h2>{query ? `Resultados para “${query}”` : 'Avisos disponíveis'}</h2><span>{results.length} avisos</span></div><div className="listing-grid">{results.map((l) => <ListingCard key={l.id} listing={l} onOpen={setSelected} />)}</div>{results.length === 0 && <div className="empty">Nenhum aviso encontrado. Tente uma nova busca.</div>}</section>}
    {screen === 'post' && <section className="page form-page"><button className="back" onClick={() => changeScreen('home')}>← Voltar</button><div className="form-heading"><p className="eyebrow">📌 COLAR NO MURAL</p><h1>Compartilhe algo<br /><em>com a comunidade.</em></h1><p>Seu aviso ficará disponível por 24 horas.</p></div><form onSubmit={publish} className="post-form"><label>Tipo de aviso<div className="type-options">{['Ofereço', 'Procuro', 'Promoção', 'Evento', 'Conexão'].map((type, i) => <label key={type}><input required defaultChecked={i === 0} type="radio" name="type" value={type} /><span>{type}</span></label>)}</div></label><label>Categoria<select name="category" required><option value="Serviços">Serviços</option><option>Produtos</option><option>Procuro</option><option>Promoções</option><option>Eventos</option><option>Conexões</option></select></label><label>Título do seu aviso<input name="title" maxLength={70} required placeholder="Ex.: Designer disponível para projetos" /></label><label>Descreva seu aviso<textarea name="description" maxLength={600} required placeholder="Conte os detalhes. O que você oferece ou procura?" rows={5} /></label><div className="two-fields"><label>Como quer aparecer no mural?<input name="name" placeholder="Seu nome ou nome do negócio" /></label><label>Preço (opcional)<input name="price" placeholder="Ex.: A combinar" /></label></div><div className="two-fields"><label>WhatsApp (opcional)<input name="whatsapp" type="tel" placeholder="(67) 99999-9999" /></label><label>Instagram (opcional)<input name="instagram" placeholder="@seuperfil" /></label></div><label>Link geral (opcional)<input name="link" type="url" placeholder="https://seusite.com.br" /></label><div className="two-fields"><label>Cidade (opcional)<input name="city" placeholder="Dourados" /></label><label>Estado<select name="state"><option>MS</option><option>SP</option><option>PR</option><option>Outro</option></select></label></div><label className="consent"><input required type="checkbox" /> <span>Declaro que sou responsável pelo conteúdo e que ele segue as regras do Mural.</span></label><button className="primary" type="submit">📌 Colar no mural</button><p className="privacy">Ao publicar, você entende que seus dados de contato ficarão públicos durante o período do aviso.</p></form></section>}
    {screen === 'promos' && <section className="page"><button className="back" onClick={() => changeScreen('home')}>← Voltar</button><div className="banner"><p>🔥 PROMOÇÕES DO DIA</p><h1>Ofertas que merecem<br /><em>ser encontradas.</em></h1><span>Atualizadas pela comunidade</span></div><div className="listing-grid">{listings.filter((l) => l.featured || l.category === 'Produtos').map((l) => <ListingCard key={l.id} listing={{ ...l, type: 'PROMOÇÃO', accent: 'yellow' }} onOpen={setSelected} />)}</div></section>}
    {screen === 'more' && <section className="page narrow"><button className="back" onClick={() => changeScreen('home')}>← Voltar</button><p className="eyebrow">☰ MAIS DO MURAL</p><h1>Encontre sua<br /><em>comunidade.</em></h1><div className="more-list"><button onClick={() => changeScreen('search')}><span>♡</span><div><b>Conexões</b><small>Conheça pessoas com afinidades em comum.</small></div><i>→</i></button><button><span>♧</span><div><b>Comunidades</b><small>Entre em grupos e espaços parceiros.</small></div><i>→</i></button><button onClick={() => { setActiveCategory('Eventos'); changeScreen('search'); }}><span>✦</span><div><b>Avisos e eventos</b><small>Fique por dentro do que está acontecendo.</small></div><i>→</i></button><button><span>?</span><div><b>Regras do Mural</b><small>Como manter este espaço seguro e útil.</small></div><i>→</i></button></div></section>}
    <nav className="mobile-nav" aria-label="Navegação móvel"><button className={screen === 'home' ? 'active' : ''} onClick={() => changeScreen('home')}>⌂<small>Início</small></button><button className={screen === 'search' ? 'active' : ''} onClick={() => changeScreen('search')}>⌕<small>Buscar</small></button><button className="post-fab" onClick={() => changeScreen('post')}>📌<small>Colar no<br />mural</small></button><button className={screen === 'promos' ? 'active' : ''} onClick={() => changeScreen('promos')}>♨<small>Promoções</small></button><button className={screen === 'more' ? 'active' : ''} onClick={() => changeScreen('more')}>☰<small>Mais</small></button></nav>
    {(selected || published) && <div className="modal-layer" role="dialog" aria-modal="true" aria-label="Detalhes do aviso"><div className="modal"><button className="modal-close" onClick={() => { setSelected(null); setPublished(null); }}>×</button>{published ? <><div className="success-mark">✓</div><p className="eyebrow">AVISO PUBLICADO</p><h2>Seu aviso foi<br />colado com sucesso!</h2><p>Ele ficará disponível por 24 horas e será visto por toda a comunidade.</p><ListingCard listing={published} onOpen={() => undefined} /><div className="share-row"><button>◉ WhatsApp</button><button>🔗 Copiar link</button></div><button className="primary" onClick={() => { setPublished(null); changeScreen('home'); }}>Ver meu aviso no mural</button></> : selected && <><span className="tag">{selected.type}</span><h2>{selected.title}</h2><p>{selected.description}</p><div className="detail-info"><span>⌖ {selected.city}</span><span>◷ {selected.hours}h restantes</span>{selected.price && <strong>{selected.price}</strong>}</div><a className="contact" href="https://wa.me/5567999998888" target="_blank">◉ Falar pelo WhatsApp <span>→</span></a><button className="secondary" onClick={() => setSelected(null)}>Voltar ao mural</button></>}</div></div>}
  </main>;
}

